// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttimhqujqjmmlnbzoios.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0aW1ocXVqcWptbWxuYnpvaW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNjM3NDksImV4cCI6MjA1NzczOTc0OX0.4cAgX-q63l-Kf3rZSepYWJ3Spbm8lO3QB2qoLLhIhNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);